export default {
  custom_items: [
    {
      internal_name: 'item_necronomicon_legacy',
      english_name: 'Necronomicon',
      chinese_name: '死灵书',
      english_aliases: ['Necrobook', 'Necro Book', 'Necronomicon 1', 'Necronomicon 2', 'Necronomicon 3'],
      chinese_aliases: ['死灵书', '小死灵书', '大死灵书'],
      deprecated: true,
    },
  ],
  custom_terms: [
    {
      internal_name: 'term_tormentor',
      english_name: 'Tormentor',
      chinese_name: '痛苦魔方',
      english_aliases: ['Tormentor', 'Tormentors'],
      chinese_aliases: ['魔方', '焦哥'],
    },
    {
      internal_name: 'term_facet',
      english_name: 'Facet',
      chinese_name: '命石',
      english_aliases: ['Facet', 'Facets', 'Aspect', 'Aspects'],
      chinese_aliases: [],
    },
  ],
  heroes: {
    'Anti-Mage': { chinese_aliases: ['敌法'] },
    Axe: { chinese_aliases: ['斧子'] },
    'Ancient Apparition': { chinese_aliases: ['冰魂'] },
    Batrider: { chinese_aliases: ['蝙蝠'] },
    Bloodseeker: { chinese_aliases: ['血魔'] },
    'Bounty Hunter': { chinese_aliases: ['赏金'] },
    Broodmother: { chinese_aliases: ['蜘蛛'] },
    'Centaur Warrunner': { chinese_aliases: ['人马', '半人马'] },
    Clinkz: { chinese_aliases: ['小骷髅'] },
    Clockwerk: { chinese_aliases: ['发条'] },
    'Crystal Maiden': { chinese_aliases: ['冰女'] },
    'Dark Seer': { chinese_aliases: ['黑贤'] },
    Dazzle: { chinese_aliases: ['戴泽'] },
    Disruptor: { chinese_aliases: ['萨尔'] },
    Doom: { chinese_aliases: ['末日'], english_aliases: ['Doom Bringer', 'Doom Bringer Hero'] },
    'Dragon Knight': { chinese_aliases: ['龙骑'], english_aliases: ['DK'] },
    'Drow Ranger': { chinese_aliases: ['小黑'], english_aliases: ['Traxex'] },
    'Earth Spirit': { chinese_aliases: ['土猫'] },
    Earthshaker: { chinese_aliases: ['小牛'] },
    'Elder Titan': { chinese_aliases: ['大牛'] },
    'Ember Spirit': { chinese_aliases: ['火猫'] },
    Grimstroke: { chinese_aliases: ['墨客'] },
    Gyrocopter: { chinese_aliases: ['飞机'] },
    Hoodwink: { chinese_aliases: ['松鼠'] },
    Huskar: { chinese_aliases: ['神灵'] },
    Invoker: { chinese_aliases: ['卡尔'] },
    Io: { chinese_aliases: ['小精灵'] },
    Jakiro: { chinese_aliases: ['双头龙'] },
    Juggernaut: { chinese_aliases: ['剑圣'] },
    'Keeper of the Light': { chinese_aliases: ['光法'] },
    Kunkka: { chinese_aliases: ['船长'] },
    'Legion Commander': { chinese_aliases: ['军团'] },
    Leshrac: { chinese_aliases: ['老鹿'] },
    Lifestealer: { chinese_aliases: ['小狗'] },
    Lina: { chinese_aliases: ['火女'] },
    'Lone Druid': { chinese_aliases: ['熊德', '德鲁伊'] },
    Luna: { chinese_aliases: ['月骑'] },
    Magnus: { chinese_aliases: ['猛犸'] },
    Medusa: { chinese_aliases: ['一姐'] },
    Mirana: { chinese_aliases: ['白虎'] },
    'Monkey King': { chinese_aliases: ['猴子', '大圣'] },
    Morphling: { chinese_aliases: ['水人'] },
    'Naga Siren': { chinese_aliases: ['娜迦', '小娜迦'] },
    "Nature's Prophet": { chinese_aliases: ['先知'], english_aliases: ['Furion'] },
    Necrophos: { chinese_aliases: ['NEC', '死灵法'], english_aliases: ['Necrolyte', 'Necro'] },
    'Night Stalker': { chinese_aliases: ['夜魔'] },
    'Nyx Assassin': { chinese_aliases: ['小强'] },
    'Ogre Magi': { chinese_aliases: ['蓝胖'] },
    Omniknight: { chinese_aliases: ['全能'] },
    'Outworld Destroyer': { chinese_aliases: ['黑鸟'], english_aliases: ['Outworld Devourer'] },
    Pangolier: { chinese_aliases: ['滚滚'] },
    'Phantom Assassin': { chinese_aliases: ['幻刺'] },
    Phoenix: { chinese_aliases: ['凤凰'] },
    Puck: { chinese_aliases: ['精灵龙'] },
    Pudge: { chinese_aliases: ['屠夫', '胖子'] },
    Pugna: { chinese_aliases: ['骨法'] },
    'Queen of Pain': { chinese_aliases: ['女王'], english_aliases: ['QOP'] },
    Razor: { chinese_aliases: ['电魂'] },
    Riki: { chinese_aliases: ['隐刺'] },
    Rubick: { chinese_aliases: ['拉比克'] },
    'Sand King': { chinese_aliases: ['沙王'], english_aliases: ['SK'] },
    'Shadow Demon': { chinese_aliases: ['毒狗'] },
    'Shadow Fiend': { chinese_aliases: ['影魔'], english_aliases: ['Nevermore', 'SF'] },
    'Shadow Shaman': { chinese_aliases: ['小Y'], english_aliases: ['Rhasta'] },
    Silencer: { chinese_aliases: ['沉默'] },
    'Skywrath Mage': { chinese_aliases: ['天怒'] },
    Slardar: { chinese_aliases: ['大鱼人'] },
    Slark: { chinese_aliases: ['小鱼人'] },
    Snapfire: { chinese_aliases: ['奶奶'] },
    Sniper: { chinese_aliases: ['火枪'] },
    Spectre: { chinese_aliases: ['幽鬼'] },
    'Spirit Breaker': { chinese_aliases: ['白牛'] },
    'Storm Spirit': { chinese_aliases: ['蓝猫'] },
    Sven: { chinese_aliases: ['流浪剑客'] },
    Techies: { chinese_aliases: ['炸弹人'] },
    'Templar Assassin': { chinese_aliases: ['圣堂'] },
    Terrorblade: { chinese_aliases: ['TB', '魂守'] },
    Tidehunter: { chinese_aliases: ['潮汐'] },
    Timbersaw: { chinese_aliases: ['伐木机'] },
    Tinker: { chinese_aliases: ['TK', '修补匠'] },
    'Treant Protector': { chinese_aliases: ['大树'] },
    Tusk: { chinese_aliases: ['海民'] },
    Undying: { chinese_aliases: ['尸王'] },
    Ursa: { chinese_aliases: ['拍拍熊'] },
    'Vengeful Spirit': { chinese_aliases: ['复仇'], english_aliases: ['VS'] },
    Venomancer: { chinese_aliases: ['剧毒'] },
    Viper: { chinese_aliases: ['毒龙'] },
    Visage: { chinese_aliases: ['死灵龙'] },
    'Void Spirit': { chinese_aliases: ['紫猫'] },
    Weaver: { chinese_aliases: ['蚂蚁'] },
    Windranger: { chinese_aliases: ['风行'], english_aliases: ['Windrunner', 'WR'] },
    'Winter Wyvern': { chinese_aliases: ['冰龙', '冬龙'] },
    'Witch Doctor': { chinese_aliases: ['巫医'] },
    'Wraith King': { chinese_aliases: ['骷髅王'], english_aliases: ['Skeleton King', 'WK'] },
    Zeus: { chinese_aliases: ['众神之王'] },
  },
  items: {
    'Aghanim’s Scepter': { english_aliases: ["Aghanim's Scepter", 'Aghs', 'Scepter'], chinese_aliases: ['A杖'] },
    'Aghanim’s Shard': {
      preferred_chinese_name: '魔晶',
      english_aliases: ["Aghanim's Shard", 'Shard', 'Shards'],
      chinese_aliases: ['魔晶'],
    },
    'Arcane Boots': { chinese_aliases: ['秘法鞋', '秘法'] },
    'Assault Cuirass': { english_aliases: ['AC'], chinese_aliases: ['强袭'] },
    'Abyssal Blade': { chinese_aliases: ['深渊刀', '深渊'] },
    'Battle Fury': { english_aliases: ['BF'], chinese_aliases: ['狂战斧'] },
    'Black King Bar': { english_aliases: ['BKB'], chinese_aliases: ['黑皇杖'] },
    'Blink Dagger': { english_aliases: ['Blink'], chinese_aliases: ['跳刀'] },
    'Blade Mail': { english_aliases: ['BM'], chinese_aliases: ['刃甲'] },
    'Bloodstone': { chinese_aliases: ['血精石'] },
    'Boots of Travel': { english_aliases: ['BoT', 'BoTs'], chinese_aliases: ['飞鞋'] },
    'Crimson Guard': { chinese_aliases: ['赤红甲', '赤红'] },
    Daedalus: { chinese_aliases: ['大炮'] },
    Desolator: { chinese_aliases: ['黯灭'] },
    'Diffusal Blade': { chinese_aliases: ['散失'] },
    'Divine Rapier': { chinese_aliases: ['圣剑'] },
    'Drum of Endurance': { english_aliases: ['Drums'], chinese_aliases: ['战鼓'] },
    'Echo Sabre': { chinese_aliases: ['回音刀'] },
    "Eul's Scepter of Divinity": { english_aliases: ['Euls'], chinese_aliases: ['风杖'] },
    'Eye of Skadi': { chinese_aliases: ['冰眼'] },
    'Force Staff': { chinese_aliases: ['推推', '推推棒'] },
    'Glimmer Cape': { chinese_aliases: ['微光'] },
    Gleipnir: { chinese_aliases: ['缚灵索'] },
    'Guardian Greaves': { chinese_aliases: ['大鞋'] },
    "Heaven's Halberd": { chinese_aliases: ['天堂之戟'] },
    'Hand of Midas': { chinese_aliases: ['点金手', '点金'] },
    'Heart of Tarrasque': { chinese_aliases: ['龙心'] },
    'Hurricane Pike': { chinese_aliases: ['飓风长戟', 'Pike'] },
    "Linken's Sphere": { english_aliases: ['Linkens'], chinese_aliases: ['林肯'] },
    'Lotus Orb': { chinese_aliases: ['莲花'] },
    Maelstrom: { english_aliases: ['Mael'], chinese_aliases: ['电锤'] },
    Manta: { english_aliases: ['Manta Style'], chinese_aliases: ['分身斧', '幻影斧'] },
    Mjollnir: { chinese_aliases: ['雷神之锤'] },
    'Monkey King Bar': { english_aliases: ['MKB'], chinese_aliases: ['金箍棒'] },
    Nullifier: { chinese_aliases: ['否决坠饰'] },
    'Octarine Core': { chinese_aliases: ['玲珑心'] },
    Orchid: { english_aliases: ['Orchid Malevolence'], chinese_aliases: ['紫怨'] },
    'Phase Boots': { chinese_aliases: ['相位鞋', '相位'] },
    'Pipe of Insight': { chinese_aliases: ['笛子'] },
    'Power Treads': { english_aliases: ['PT', 'Treads'], chinese_aliases: ['假腿'] },
    'Radiance': { chinese_aliases: ['辉耀'] },
    'Refresher Orb': { english_aliases: ['Refresher'], chinese_aliases: ['刷新球'] },
    'Refresher Shard': { chinese_aliases: ['刷新碎片'] },
    'Rod of Atos': { english_aliases: ['Atos'], chinese_aliases: ['阿托斯'] },
    Satanic: { chinese_aliases: ['撒旦'] },
    'Scythe of Vyse': { english_aliases: ['Hex'], chinese_aliases: ['羊刀'] },
    'Shadow Blade': { chinese_aliases: ['隐刀'] },
    'Silver Edge': { chinese_aliases: ['大隐刀'] },
    'Skull Basher': { english_aliases: ['Basher'], chinese_aliases: ['碎骨锤'] },
    'Spirit Vessel': { chinese_aliases: ['大骨灰', '灵龛'] },
    'Tranquil Boots': { chinese_aliases: ['绿鞋'] },
    'Urn of Shadows': { chinese_aliases: ['骨灰'] },
    Wand: { english_aliases: ['Magic Wand'], chinese_aliases: ['魔棒'] },
  },
  abilities: {
    "Berserker's Call": { english_aliases: ['Call'], chinese_aliases: ['吼'] },
    'Black Hole': { chinese_aliases: ['黑洞'] },
    'Chronosphere': { english_aliases: ['Chrono'], chinese_aliases: ['大招罩', '时间结界'] },
    'Culling Blade': { english_aliases: ['Cull'], chinese_aliases: ['淘汰', '斩杀'] },
    'Dream Coil': { english_aliases: ['Coil'], chinese_aliases: ['梦境缠绕'] },
    Duel: { chinese_aliases: ['决斗'] },
    Doom: { chinese_aliases: ['末日'] },
    'Echo Slam': { english_aliases: ['Echo'], chinese_aliases: ['沟壑大', '回音击'] },
    'Fiend’s Grip': { english_aliases: ["Fiend's Grip"], chinese_aliases: ['大招拉', '魔爪'] },
    'Finger of Death': { english_aliases: ['Finger'], chinese_aliases: ['死亡一指'] },
    'Global Silence': { chinese_aliases: ['全球流', '全图沉默'] },
    'Hookshot': { chinese_aliases: ['发条大'] },
    'Laguna Blade': { english_aliases: ['Laguna'], chinese_aliases: ['神灭斩'] },
    'Meat Hook': { english_aliases: ['Hook'], chinese_aliases: ['钩子'] },
    Ravage: { chinese_aliases: ['大海啸'] },
    'Reverse Polarity': { english_aliases: ['RP'], chinese_aliases: ['两极反转'] },
    'Reaper’s Scythe': { english_aliases: ["Reaper's Scythe", 'Reaper'], chinese_aliases: ['镰刀'] },
    'Shackleshot': { english_aliases: ['Shackle'], chinese_aliases: ['束缚击'] },
    'Static Storm': { chinese_aliases: ['静态风暴'] },
    Supernova: { english_aliases: ['Egg'], chinese_aliases: ['变蛋'] },
    'Teleportation': { chinese_aliases: ['飞'] },
  },
};
